name: Vuedc CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  STORE_PATH: ""

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call-env-setup:
    uses: "./.github/workflows/env-setup.yml"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [call-env-setup]
    steps:
      - name: Lint code
        run: pnpm lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [call-env-setup]
    steps:
      - name: Unittests
        run: pnpm test
